#version: "3"
services:
  nextclouddb:
    image: mariadb:10.7.1
    container_name: nextclouddb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --skip-innodb-read-only-compressed
    volumes:
      - ${appdata}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - dockernet

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - ${nextcloud_port}:80
    links:
      - nextclouddb
      - redis
    volumes:
      - ${appdata}/html:/var/www/html
      - ${nextcloud_folder}/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=nextcloudredis
      - REDIS_HOST_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - dockernet

  redis:
    image: redis:alpine
    container_name: nextcloudredis
    command: redis-server --requirepass ${MYSQL_PASSWORD}
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true

# running OCC command
# sudo docker exec -ti --user www-data nextcloud-nextcloud-1 /var/www/html/occ files:scan userx

# Fix missing indexes
# docker exec -it -u 1000 nextcloud-nextcloud-1 /var/www/html/occ db:add-missing-indices
