services:

  broker:
    image: docker.io/library/redis:7.2
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - dockernet

  db:
    image: docker.io/library/postgres:17
    #image: pgautoupgrade/pgautoupgrade
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - ${appdata}/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    cpus: 0.5
    mem_limit: 2048m
    networks:
      - dockernet

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.18.1
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - ${paperless_port}:8000
    healthcheck:
      test:
        - CMD
        - curl
        - -fs
        - -S
        - --max-time
        - "2"
        - http://localhost:8000
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${appdata}/other:/usr/src/paperless/data
      - ${private_medias}/paperless/documents:/usr/src/paperless/media
      - ${private_medias}/paperless_backup:/usr/src/paperless/export
      - ${sharedfolder}/scan:/usr/src/paperless/consume
    environment:
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS}
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_POLLING: 30
      PAPERLESS_ENABLE_ALLAUTHH: "True"
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": "clientid",
                "secret": "secret",
                "settings": {
                "server_url": "https://authentik.domain.com/o/paperless/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }
    #cpus: 0.5
    #mem_limit: 1024m
    networks:
      - dockernet

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.6
    container_name: paperless-gotenberg
    restart: unless-stopped
    command:
      - gotenberg
      - --chromium-disable-routes=true
    networks:
      - dockernet

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperless-tika
    restart: unless-stopped
    networks:
      - dockernet

volumes:
  redisdata: null

networks:
  dockernet:
    external: true
